'use strict';
const $ = id => document.getElementById(id);
const names = {baseline:'Rules baseline',jev:'Jev',laya:'Laya',clm:'CLM-8B'};
const fields = {initial_owner:'Initial owner',priority:'Priority',next_check:'Next check',insufficient_evidence:'Insufficient evidence'};
let config={}, incidents=[], job=null, timer=null, selected=new Set(['baseline']);
const esc = v => String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct = v => v==null ? '—' : (v*100).toFixed(1)+'%';
const latency = v => v==null ? '—' : v<1 ? '<1 ms' : v<1000 ? v.toFixed(0)+' ms' : (v/1000).toFixed(2)+' s';
function notice(message){$('notice').textContent=message;$('notice').hidden=!message;}
async function api(path,data){const r=await fetch(path,data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{});const body=await r.json();if(!r.ok)throw new Error(body.error||'Request failed');return body;}
function renderModels(){
 $('modelChoices').innerHTML=Object.keys(names).map(p=>`<label><input type="checkbox" value="${p}" ${selected.has(p)?'checked':''}>${names[p]}</label>`).join('');
 $('modelChoices').querySelectorAll('input').forEach(el=>el.onchange=()=>{el.checked?selected.add(el.value):selected.delete(el.value);});
}
async function loadIncidents(id){incidents=await api('/api/incidents?split='+$('split').value);$('datasetInfo').textContent=incidents.length+' available incidents';$('incident').innerHTML=incidents.map((r,i)=>`<option value="${r.id}">${String(i+1).padStart(3,'0')} · ${esc(r.family.replaceAll('_',' '))}</option>`).join('');if(id&&incidents.some(r=>r.id===id))$('incident').value=id;showIncident();}
function showIncident(){const r=incidents.find(i=>i.id===$('incident').value);if(!r)return;const impact=r.input.service_impact;$('impact').innerHTML=`<span class="badge subtle">${esc(impact.status)}</span><span class="badge subtle">${impact.affected_sites??'Unknown'} affected sites</span><span class="badge subtle">${esc(r.input.decision_timestamp)}</span>`;$('observation').textContent=r.input.ticket.description;$('packet').textContent=JSON.stringify(r.input,null,2);$('labels').innerHTML=Object.entries(r.labels).map(([k,v])=>`<dt>${fields[k]}</dt><dd>${esc(v)}</dd>`).join('');renderDecisions();}
function renderSummary(){
 $('summary').innerHTML=Object.keys(names).map(p=>{const result=job?.results?.[p], m=result?.metrics;return `<tr><td><span class="modelname">${names[p]}</span><span class="deployment">${esc(result?.metadata?.deployment|| (p==='jev'&&!config.jev?.key_configured?'Add API key in settings':p==='baseline'?'Local deterministic rules': 'Endpoint: '+(config[p]?.endpoint||'not configured')))}</span></td><td class="metric">${pct(m?.all_fields_accuracy)}</td><td>${pct(m?.fields?.initial_owner?.accuracy)}</td><td>${pct(m?.p1_miss_rate)}</td><td class="num">${latency(m?.successful_latency_ms?.p95)}</td><td>${m?m.failed_records+' / '+m.missing_records:result?.error?'Run error':'Not run'}</td></tr>`;}).join('');
 if(job){$('resultContext').textContent=`${job.split} · ${job.count} incident${job.count===1?'':'s'} · ${job.status.replaceAll('_',' ')} · Responses include network and serving time. Small samples do not establish a model ranking.`;$('download').disabled=false;}
}
function renderDecisions(){const r=incidents.find(i=>i.id===$('incident').value);if(!r||!job){$('decisions').innerHTML='<p class="empty">Run an incident to see the decisions, answer probabilities, and disagreements here.</p>';return;}
 $('recordStatus').textContent=job.split===$('split').value?'Measured predictions':'Different split selected';
 $('decisions').innerHTML=job.providers.map(p=>{const result=job.results[p];const row=result?.predictions?.find(x=>x.id===r.id);let body='';
 if(result?.error)body=`<p class="error">${esc(result.error)}</p>`;
 else if(!row)body='<p class="muted">This incident has not been evaluated in this run.</p>';
 else if(row.status!=='ok')body=`<p class="error">${esc(row.error||'Request failed')}</p>`;
 else body=Object.keys(fields).map(f=>{const choice=row.predictions[f],correct=choice===r.labels[f],dist=row.probabilities?.[f];return `<div class="decisionrow"><span>${fields[f]}</span><strong class="${correct?'correct':'incorrect'}">${esc(choice)} ${correct?'✓':'✕'}</strong></div>${dist?`<details><summary class="probability">Answer probabilities · selected ${pct(dist[choice])}</summary>${Object.entries(dist).map(([k,v])=>`<div class="decisionrow"><span>${esc(k)}</span><span>${pct(v)}</span></div><meter min="0" max="1" value="${v}"></meter>`).join('')}</details>`:''}`;}).join('');
 return `<div class="decisioncard"><div class="decisionhead"><strong>${names[p]}</strong><span class="muted">${row?.status==='ok'?latency(row.latency_ms):'—'}</span></div>${body}${row?.resolved_model?'<p class="hint">Resolved model: '+esc(row.resolved_model)+'</p>':''}</div>`;}).join('');
}
function lockRun(active){$('runBatch').disabled=active;$('runSingle').disabled=active;$('progressPanel').hidden=!active;}
async function refreshHistory(){const jobs=await api('/api/jobs');$('history').innerHTML='<option value="">Choose a comparison</option>'+jobs.map(j=>`<option value="${j.id}">${esc(j.created_at.slice(5,16).replace('T',' '))} · ${j.split} · ${j.count} cases</option>`).join('');if(job)$('history').value=job.id;}
async function poll(){try{job=await api('/api/jobs/'+job.id);renderSummary();renderDecisions();const active=['queued','running'].includes(job.status);lockRun(active);$('progress').max=job.total;$('progress').value=job.completed;$('progressText').textContent=`${job.completed} / ${job.total} requests${job.current_provider?' · '+names[job.current_provider]:''}`;if(active)timer=setTimeout(poll,800);else{timer=null;await refreshHistory();if(job.status==='completed_with_errors')notice('Some model requests failed. Inspect the incident results and check server settings.');}}catch(e){lockRun(false);notice(e.message);}}
async function start(single){try{notice('');const split=$('split').value;const payload={split,providers:[...selected]};if(single)payload.record_id=$('incident').value;else payload.count=$('count').value==='all'?incidents.length:Number($('count').value);job=await api('/api/jobs',payload);if(timer)clearTimeout(timer);lockRun(true);await refreshHistory();await poll();}catch(e){notice(e.message);}}
function fillSettings(){const p=$('provider').value,c=config[p];$('model').value=c.model;$('endpoint').value=c.endpoint;$('capacity').value=c.context_tokens;$('deployment').value=c.deployment;$('apiKey').value='';$('clearKey').checked=false;$('keyState').textContent=c.key_configured?'· key configured':'· no key stored';$('settingsError').textContent='';$('setupHint').textContent=p==='jev'?'Paste your Jev key here. It is kept only in this server process. An alias such as jev-latest can change; use a pinned version for repeatable tests.':p==='laya'?'No vendor key needed. In a terminal, run scripts/setup_laya.sh, then scripts/start_laya.sh. This serves the multilingual checkpoint with an 8,192-token limit on port 8000.': 'No vendor key needed. On your 36 GB Apple Silicon Mac, run scripts/setup_clm_mac.sh, then scripts/start_clm_mac.sh. This uses MLX and the original CLM head. See docs/app.md for bf16 and 8-bit options.';}
$('settingsButton').onclick=()=>{fillSettings();$('settings').showModal();};$('closeSettings').onclick=()=>{$('apiKey').value='';$('settings').close();};$('provider').onchange=fillSettings;
$('settingsForm').onsubmit=async e=>{e.preventDefault();try{config=await api('/api/config',{provider:$('provider').value,model:$('model').value,endpoint:$('endpoint').value,context_tokens:Number($('capacity').value),deployment:$('deployment').value,api_key:$('apiKey').value,clear_key:$('clearKey').checked});$('apiKey').value='';$('settings').close();renderSummary();notice('Settings saved for this server session.');}catch(error){$('settingsError').textContent=error.message;}};
function updateBatchSizes(){const challenge=$('split').value==='challenge';$('count').innerHTML=challenge?'<option value="4">4 incidents · 2 pairs</option><option value="all">All 24 incidents</option>':'<option value="5">5 incidents · smoke test</option><option value="20">20 incidents</option><option value="all">Full split</option>';}
$('split').onchange=async()=>{updateBatchSizes();try{await loadIncidents();}catch(e){notice(e.message);}};
$('incident').onchange=showIncident;$('runBatch').onclick=()=>start(false);$('runSingle').onclick=()=>start(true);
$('cancelRun').onclick=async()=>{try{await api('/api/cancel',{id:job.id});notice('Cancellation requested. The current request may take up to its timeout to finish.');}catch(e){notice(e.message);}};
$('history').onchange=async()=>{if(!$('history').value)return;try{if(timer)clearTimeout(timer);job=await api('/api/jobs/'+$('history').value);$('split').value=job.split;updateBatchSizes();await loadIncidents(job.results?.[job.providers[0]]?.predictions?.[0]?.id);await poll();}catch(e){notice(e.message);}};
$('download').onclick=()=>{if(!job)return;const url=URL.createObjectURL(new Blob([JSON.stringify(job,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`northstar-${job.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
(async()=>{try{config=await api('/api/config');renderModels();await loadIncidents();renderSummary();await refreshHistory();}catch(e){notice(e.message);}})();
