"""New authored training mechanisms; never an independently sourced holdout.

Each row contains two factual variants. Expected dispositions are provisional
author references only. The live teacher receives neither those references nor
the family names. Themes intentionally overlap development interventions.
"""

# family | domain | current supporting evidence | current non-supporting evidence
DOMAIN_PAIRS = '''radio_baseband_memory|ran|The baseband diagnostic independently reproduces uncorrectable memory faults when the affected sector processes traffic; local radio KPIs degrade at those instants.|The baseband diagnostic finds no memory fault and radio KPIs are normal; a historical memory alarm has no current corroboration.
radio_fronthaul_clock|ran|Local fronthaul timing checks reproduce a phase slip between the radio unit and baseband; independent sector timing measurements confirm it.|Local fronthaul timing and independent sector timing measurements pass; an earlier phase-slip notification is not current.
radio_amplifier_gain|ran|Independent RF bench checks confirm gain compression in the sector power amplifier while the commanded input remains stable.|Independent RF bench checks confirm normal gain in the sector power amplifier; the previous gain-compression warning is cleared.
radio_uplink_decoder|ran|Two independent decoder traces show failed uplink block processing inside the radio baseband despite normal incoming signal quality.|Two independent decoder traces show normal uplink block processing and incoming signal quality; the decoder warning has no current supporting measurement.
radio_duplex_filter|ran|Independent RF sweeps reproduce excessive loss in the duplex filter on the affected antenna chain; sector link measurements agree.|Independent RF sweeps and sector link measurements show normal duplex-filter loss; an old filter warning is not reproduced.
radio_remote_cooling|ran|Independent temperature probes and a local hardware diagnostic confirm radio-unit thermal shutdown with a stalled cooling fan.|Independent temperature probes show normal radio-unit temperature and the local cooling-fan diagnostic passes; the thermal warning is historical.
transport_spanning_loop|transport|Independent packet captures reproduce a forwarding loop on the shared switching path and show affected frames repeatedly revisiting the same switch.|Independent captures show affected frames traversing the shared switching path once without a forwarding loop; historical loop notifications are not current.
transport_tunnel_binding|transport|Independent tunnel traces confirm affected packets are delivered to the wrong tunnel endpoint because the shared transport binding differs from the verified intended path.|Independent traces confirm packets reach the intended tunnel endpoint and the shared transport binding matches the verified path; the earlier binding warning is not reproduced.
transport_label_disposition|transport|Independent ingress and egress traces confirm the common forwarding node drops affected packets at an invalid label disposition; adjacent paths pass.|Independent ingress and egress traces confirm valid label disposition and no drop at the common forwarding node; an old label error is not reproduced.
transport_microburst_buffer|transport|Two independent captures align short traffic bursts with shared-switch buffer overflow and lost packets, despite low average utilization.|Two independent captures show no buffer overflow or packet loss during the short traffic bursts at the shared switch; low average utilization alone is inconclusive.
transport_pseudowire_sequence|transport|Independent traces show the shared pseudowire receiver rejects valid frames because its sequence state diverges; affected frames are lost there.|Independent traces show matching pseudowire sequence state and no receiver rejection; the stale sequence alert does not describe current traffic.
transport_dependency_membership|transport|The alarmed uplink is on every affected site's path in the verified complete dependency graph; current independent uplink diagnostics confirm loss of signal.|The alarmed uplink is absent from every affected site's path in the verified complete dependency graph; current independent uplink diagnostics confirm loss of signal on that unrelated link.
power_busbar_joint|power|A field resistance measurement and an independent thermal image confirm a high-resistance busbar joint and voltage loss at the equipment feed.|A field resistance measurement and an independent thermal image show a normal busbar joint and equipment-feed voltage; the earlier warning is not reproduced.
power_remote_feed|power|Independent readings at both ends of the remote DC feed confirm a cable discontinuity and no voltage at the downstream equipment.|Independent readings at both ends of the remote DC feed confirm continuity and normal equipment voltage; a historical cable warning lacks current support.
power_earth_fault|power|Independent insulation and leakage-current measurements reproduce an earth fault on the equipment supply branch and confirm protective isolation.|Independent insulation and leakage-current measurements pass for the equipment branch; protective isolation is not present and the earlier earth-fault alarm is stale.
power_inverter_bypass|power|Independent output-waveform measurements reproduce an unstable inverter bypass transfer that interrupts the equipment feed.|Independent output-waveform measurements confirm stable inverter bypass transfer and no feed interruption; an earlier transfer notification is not current.
power_voltage_sensor_disagreement|power|Independent calibrated meters and the controller agree that equipment supply voltage is below its operating range.|The controller reports low equipment supply voltage while two calibrated meters report normal voltage at the same feed and time; the disagreement is explicitly unresolved.
power_dc_polarity|power|Independent field measurements confirm reversed polarity at the equipment supply connector and the input protection blocks power.|Independent field measurements confirm correct polarity and operating voltage at the equipment supply connector; an earlier polarity warning lacks current support.
core_replica_quorum|core|Independent shared-service traces confirm requests fail because the registration-store replicas cannot form a quorum; direct service checks reproduce it across independent access paths.|Independent registration-store traces confirm healthy replica quorum and direct service checks pass; distributed symptoms alone do not establish a core fault.
core_lease_lock|core|Independent traces reproduce an unreleased lock in the shared session lease service that blocks affected requests arriving over distinct access paths.|Independent session lease traces show no unreleased lock and direct service checks pass; an old lock notification is not current.
core_api_schema|core|Independent service traces reproduce schema rejection at the shared core API for otherwise valid requests from distinct access paths.|Independent core API traces accept the requests and schema checks pass; the prior rejection log is historical and no current core failure is observed.
core_replica_read_skew|core|Independent service traces reproduce inconsistent replica reads in the shared subscriber service, and direct requests over separate access paths fail there.|Independent subscriber-service traces show consistent replica reads and direct requests pass; no current shared-service diagnosis is supported.
core_rate_limit_scope|core|Independent request traces reproduce an incorrectly shared rate-limit bucket in the core service that rejects low-rate requests from separate access paths.|Independent request traces show separate rate-limit buckets and no rejection in the core service; cross-site symptoms alone do not identify its cause.
core_endpoint_pool|core|Independent direct probes and request traces confirm the shared registration endpoint pool sends requests to unavailable workers while healthy alternate workers succeed.|Independent direct probes and request traces show the registration endpoint pool uses available workers and requests pass; a stale worker alarm is not current.
'''

# family | approved/actual scope ambiguity | verified fully explained planned impact
CHANGE_PAIRS = '''change_edge_acl_scope|The approved work changes an edge-access filter for S0 and S1. Four sites are unreachable, including S2 and S3. The applied asset list is unverified and no current domain diagnosis is available.|Independent work logs verify the approved edge-access-filter work was applied only to S0 and S1. Service suspension at those two sites fully matches the planned work; all other sites pass and there is no unplanned impact.
change_radio_license_scope|The approved work suspends radio licenses at S0 and S1. Four sites are unreachable, including S2 and S3. Actual license assignments touched by the work are unverified and no current domain diagnosis is available.|Independent work logs verify license suspension only at approved sites S0 and S1. Their planned suspension matches the verified work; all other sites pass with no unplanned impact.
change_core_drain_scope|The approved work drains service instances used by S0 and S1. Four sites are unreachable, including S2 and S3. Which instances were actually drained is unverified and no current domain diagnosis is available.|Independent work logs verify only the approved service instances for S0 and S1 were drained. Their planned suspension fully matches work scope; all other sites pass with no unplanned impact.
'''

RECOVERY_PAIRS = '''recovery_sms_transaction|The messaging alarm cleared, but no independent end-to-end SMS transaction check has arrived. Current domain diagnostics are unavailable and service impact has not been verified.|Repeated independent end-to-end SMS transactions and service counters pass for the completed required recovery interval. The messaging alarm is historical and there is no current unplanned impact.
recovery_data_session|The data-session alarm cleared, but no independent session-establishment and user-traffic check has arrived. Current domain diagnostics are unavailable and service impact has not been verified.|Repeated independent session-establishment and user-traffic checks pass for the completed required recovery interval. The historical data-session alarm is inactive with no current unplanned impact.
recovery_voice_setup|The voice-setup alarm cleared, but no independent end-to-end call-setup check has arrived. Current domain diagnostics are unavailable and service impact has not been verified.|Repeated independent call-setup checks and voice-service counters pass for the completed required recovery interval. The historical voice alarm is inactive with no current unplanned impact.
'''
