"""Paired synthetic mechanisms assigned before reviews or model scoring.

New family names identify mechanisms, not independently validated independence.
Themes overlap earlier development; these are not operational samples.
"""

# split | family | domain | supported current diagnosis | non-supporting current evidence
DOMAIN_PAIRS = '''train|radio_local_oscillator|ran|A calibrated receiver and the radio's frequency diagnostic both reproduce oscillator drift outside tolerance during affected traffic.|The calibrated receiver measures an in-tolerance oscillator and the frequency diagnostic passes; an old drift notification is not reproduced.
train|radio_adc_clipping|ran|Raw radio samples and a separate hardware loopback show ADC clipping inside the receive chain at normal input amplitude.|Raw radio samples have headroom and the hardware loopback passes at normal input amplitude; the historical ADC clipping report has no current support.
train|radio_harq_process|ran|Baseband traces and an independent traffic replay reproduce a stuck HARQ process in the local radio scheduler; uplink decoding stalls there.|Baseband traces show advancing HARQ processes and replay does not stall; the local scheduler passes and yesterday's stuck-process trace is historical.
train|radio_beam_calibration|ran|A separate field sweep reproduces wrong beam weights in the local antenna array, and its calibration diagnostic fails on the affected sector.|The field sweep and calibration diagnostic confirm correct beam weights on the affected sector; the earlier warning does not reproduce.
train|radio_carrier_mapping|ran|Two independent local traces show valid traffic mapped to a disabled radio carrier by the baseband; adjacent carriers work.|Two independent local traces show traffic mapped to enabled radio carriers and no local rejection; the previous mapping warning has cleared.
train|radio_timing_advance|ran|Independent radio traces reproduce a corrupted timing-advance table at the sector baseband, and a direct UE test loses uplink alignment there.|Independent radio traces show a valid timing-advance table and the direct UE test remains aligned; the old local table warning lacks current corroboration.
train|transport_reverse_path|transport|Captures on both sides of the shared router show valid packets rejected by reverse-path validation using the wrong interface; the rejection counter increments.|Captures show valid packets admitted by reverse-path validation on the correct interface; its rejection counter does not increment.
train|transport_ecmp_blackhole|transport|Ingress/egress captures and a path probe reproduce loss on one ECMP next hop in the common routed transport path; other next hops pass.|Ingress/egress captures and path probes pass on every ECMP next hop in the common transport path; a past blackhole log is not current.
train|transport_mtu_blackhole|transport|Controlled packet-size probes and matching captures reproduce a lower-than-documented MTU in the shared path that drops affected frames.|Controlled packet-size probes and captures confirm the documented MTU and delivery of affected frames; the earlier size warning is not reproduced.
train|transport_qos_policer|transport|Independent captures show conforming traffic dropped by a misbound policer at the common transport node, with synchronized counter increments.|Independent captures show conforming traffic forwarded and no policer drop increments; the misbinding claim is ruled out by the current table and traffic.
train|transport_optical_fec|transport|An optical tester and independent transceiver counters reproduce uncorrectable FEC blocks and lost payload on the common fiber span.|The optical tester sees clean payload and current transceiver counters show no uncorrectable FEC blocks; the historical span warning has cleared.
train|transport_ttl_rewrite|transport|Independent packet captures locate an incorrect TTL rewrite at the common transport router, where affected packets expire prematurely.|Independent captures show the correct TTL rewrite and affected packets leave the common router without expiry; the old rewrite report is not reproduced.
train|power_fuse_contact|power|A calibrated field voltage test and thermal scan reproduce an intermittent fuse-holder contact that removes the equipment DC feed.|The field voltage test and thermal scan show a sound fuse-holder contact and stable equipment DC feed; the earlier contact alarm is not reproduced.
train|power_rectifier_ripple|power|An oscilloscope and independent equipment-input diagnostic confirm excessive rectifier ripple at the DC feed, causing repeated input shutdown.|The oscilloscope shows in-tolerance ripple and the equipment-input diagnostic passes at the same feed; the historical ripple warning is not reproduced.
train|power_battery_isolation|power|Independent continuity and load tests locate an open battery isolator that breaks backup delivery to the equipment feed.|Independent continuity and load tests confirm the battery isolator delivers backup to the equipment feed; an old isolation alarm lacks current support.
train|power_ats_interlock|power|A field transfer test and separate status recorder reproduce a stuck ATS interlock that leaves the equipment supply disconnected.|The field transfer test and separate status recorder show the ATS interlock transfers correctly and maintains supply; the previous fault record is historical.
train|power_neutral_connection|power|A field impedance test and independent supply measurements reproduce a loose neutral connection with out-of-range equipment input voltage.|The impedance test and independent supply measurements confirm a sound neutral connection and operating equipment voltage; the old warning is not reproduced.
train|power_branch_contactor|power|A calibrated downstream meter and independent contact-position sensor agree that the equipment branch contactor remains open when commanded closed.|The downstream meter confirms operating voltage while the contact-position sensor reports the same contactor open at the same instant; the two readings are unresolved.
train|core_name_cache|core|Direct resolver queries over distinct access paths and independent server traces reproduce a poisoned name-cache entry in the shared core resolver.|Direct resolver queries and server traces return the correct name-cache entry; the historical poisoned-entry log is not current.
train|core_token_expiry|core|Independent authentication-service traces and valid direct requests reproduce premature token expiry inside the shared core service.|Authentication-service traces show correct token expiry and valid direct requests succeed; the old premature-expiry report has no current support.
train|core_worker_deadlock|core|Independent stack samples and direct requests reproduce a worker deadlock in the common session service that blocks otherwise valid transactions.|Stack samples show progressing workers and valid direct transactions pass in the session service; an earlier deadlock trace is historical.
train|core_shard_map|core|Direct subscriber lookups and independent service traces reproduce a wrong shard map in the shared core database, sending valid lookups to an absent partition.|Direct subscriber lookups resolve the correct partition and service traces confirm the shard map; the prior map warning is not reproduced.
train|core_journal_failure|core|Independent storage diagnostics and direct service writes reproduce a failed journal in the common registration service; valid writes are rejected there.|Independent storage diagnostics pass and direct registration-service writes succeed with a healthy journal; the earlier journal alert is historical.
train|core_service_clock|core|Independent clock probes and authentication traces show the shared core service clock outside tolerance, rejecting valid time-bound requests.|Clock probes show an in-tolerance service clock and authentication traces accept valid time-bound requests; the previous drift alert is not current.
development|radio_digital_predistortion|ran|A field RF sweep and independent radio loopback show the sector's digital predistortion coefficients corrupt the transmitted waveform.|The RF sweep shows a compliant waveform and radio loopback passes with correct coefficients; only yesterday's predistortion failure is recorded.
development|radio_srs_configuration|ran|Independent UE captures and baseband traces show the local sounding-reference configuration omits required uplink occasions, blocking affected users.|UE captures show the required sounding-reference occasions and baseband traces show successful uplink scheduling; the omission hypothesis is ruled out.
development|radio_pcie_dma|ran|An independent board diagnostic and replay trace locate failed DMA transfers on the local baseband PCIe link; affected traffic cannot reach the decoder.|The board diagnostic passes and replay transfers all affected traffic through the local PCIe link; the DMA warning is historical and not reproduced.
development|transport_vlan_translation|transport|Captures before and after the common switch show an incorrect VLAN translation strips affected traffic into a non-forwarded VLAN.|Captures show the documented VLAN translation and affected frames forwarded through the common switch; yesterday's VLAN warning lacks current corroboration.
development|transport_link_bundle_hash|transport|Independent captures and per-member probes show the common link-bundle hash sends affected traffic to a failed member despite healthy alternatives.|All bundle members pass probes, captures show successful delivery and the hash sends traffic to healthy members; the previous failed-member report is historical.
development|transport_mac_learning|transport|Captures and independent forwarding-table inspection locate stale MAC learning at the common switch that sends valid traffic to the wrong port.|The current forwarding table has correct MAC learning and captures show valid traffic on the right port; the stale-entry claim is not reproduced.
development|power_converter_current_limit|power|A calibrated load test and independent input recording reproduce a converter current limit below equipment demand, collapsing its DC feed.|The load test maintains operating DC voltage and the input recording shows no limiting; the earlier converter current-limit log is not reproduced.
development|power_surge_protector|power|An independent field isolation test and downstream meter locate a failed surge protector that opens the equipment supply branch.|The field isolation test passes and the downstream meter confirms normal supply through the surge protector; yesterday's failure notification is historical.
development|power_connector_resistance|power|A four-wire resistance measurement and independent thermal image locate high connector resistance and voltage loss at the equipment input.|The four-wire measurement finds normal connector resistance and the thermal image is normal; the equipment-input voltage is operating and the earlier warning is not current.
development|core_connection_pool|core|Independent application traces and direct valid requests reproduce exhaustion of the shared subscriber-service connection pool despite available database capacity.|Application traces show free pool connections and direct valid requests succeed; an old exhaustion alert does not describe the current shared service.
development|core_transaction_rollback|core|Independent direct transactions and server traces reproduce an erroneous rollback in the shared session store that rejects valid commits.|Independent direct transactions commit successfully and server traces show no erroneous rollback; the earlier session-store error is historical.
development|core_route_registry|core|Direct service lookups over distinct access paths and independent registry traces reproduce a wrong endpoint published by the common core service registry.|Direct lookups return the correct endpoint and registry traces agree; all direct service requests pass and the historical wrong-endpoint warning is not current.
'''

# split | family | approved work | unexpected observed impact / verified planned effect
CHANGE_PAIRS = '''train|change_transport_vrf_scope|isolate a test VRF serving S0 and S1
train|change_power_loadbank_scope|disconnect supply to S0 and S1 for a load-bank test
train|change_core_feature_scope|suspend a test subscriber feature serving S0 and S1
development|change_radio_carrier_scope|disable a test carrier serving S0 and S1
development|change_transport_port_scope|isolate test transport ports serving S0 and S1
'''

RECOVERY_PAIRS = '''train|recovery_roaming_attach|roaming attachment
train|recovery_enterprise_vpn|enterprise VPN transaction
train|recovery_emergency_test|authorized emergency-call test
development|recovery_iot_registration|IoT registration
development|recovery_video_session|video-session establishment
'''
